import { ARCHETYPES, CONTENT_TYPES, COPY_STATUS, GEO_STATUS, MEDIA_STATUS, ROME_CLUSTERS } from '../registry/constants.js'
import { unlockScopesForDiscovery } from './coverage.js'

function geo(lat, lng, note) {
  return { lat, lng, status: GEO_STATUS.NEEDS_QA, note }
}

function media({ audio = MEDIA_STATUS.NONE, visual = MEDIA_STATUS.NONE } = {}) {
  return {
    image: { status: MEDIA_STATUS.PLACEHOLDER, path: null },
    audio: { status: audio, path: null },
    visual: { status: visual, path: null },
  }
}

function d(n, { audio, visual, ...fields }) {
  const id = `d_rome_${String(n).padStart(2, '0')}`
  return Object.freeze({
    cityId: 'rome',
    contentType: CONTENT_TYPES.DISCOVERY,
    shortTitle: fields.shortTitle || fields.title,
    copyStatus: COPY_STATUS.PLACEHOLDER,
    relatedContentIds: [],
    avoidTags: [],
    indoorOutdoor: 'outdoor',
    weatherFit: 'any',
    crowdSensitivity: 'medium',
    urbanComfort: 'lively',
    accessNotes: '',
    lookHere: '',
    body: '',
    historicalGuardrail: '',
    assetStatus: MEDIA_STATUS.PLACEHOLDER,
    media: media({ audio, visual }),
    ...fields,
    id,
    unlockScopes: unlockScopesForDiscovery(id),
  })
}

/**
 * 30 Rome Discoveries. Metadata is structural (cluster, archetype, tags, time,
 * access, audio/visual intent). Body copy is placeholder — not final narration.
 * Coordinates are temporary for rendering and marked NEEDS_QA.
 */
export const ROME_DISCOVERIES = Object.freeze([
  d(1, {
    title: 'Aventine Keyhole',
    clusterId: ROME_CLUSTERS.AVENTINE,
    geo: geo(41.88335, 12.47755, 'Piazza dei Cavalieri di Malta, Priory of Malta gate'),
    interestTags: ['hidden-places', 'iconic-sights', 'religion-belief'],
    timeCostMin: 5,
    whyWorthIt: 'A garden gate frames St Peter’s dome as if it were placed there on purpose.',
    archetype: ARCHETYPES.VIEWPOINT,
    lookHere: 'Queue at the green door on Piazza dei Cavalieri di Malta. Put one eye to the keyhole.',
    body: 'Through the Knights of Malta garden gate, a clipped hedge-line aims at the dome of St Peter’s. The trick is alignment, not a secret tunnel.',
    accessNotes: 'Free, street-side. Often a short queue. Garden itself is not entered.',
    audio: MEDIA_STATUS.PLANNED,
    visual: MEDIA_STATUS.PLANNED,
    crowdSensitivity: 'high',
    urbanComfort: 'visitor-areas',
    historicalGuardrail: 'Do not claim the keyhole is ancient or a Knights Templar secret. It is a later garden axis.',
    intrinsicPriority: 86,
  }),
  d(2, {
    title: 'Giardino degli Aranci',
    shortTitle: 'Orange Garden',
    clusterId: ROME_CLUSTERS.AVENTINE,
    geo: geo(41.88285, 12.47935, 'Parco Savello / Giardino degli Aranci'),
    interestTags: ['nature-landscape', 'iconic-sights', 'people-everyday'],
    timeCostMin: 8,
    whyWorthIt: 'A quiet orange-garden terrace looks across the river toward St Peter’s.',
    archetype: ARCHETYPES.GARDEN,
    lookHere: 'Walk to the west parapet. The dome sits on the horizon, not in the garden.',
    body: 'Parco Savello is a public garden on the Aventine. The view is the point; the orange trees are the frame.',
    accessNotes: 'Public park hours. Free.',
    audio: MEDIA_STATUS.NONE,
    crowdSensitivity: 'medium',
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not invent a fortress-garden origin story beyond the Savelli / park layer.',
    intrinsicPriority: 70,
  }),
  d(3, {
    title: 'Santa Sabina carved doors',
    shortTitle: 'Santa Sabina doors',
    clusterId: ROME_CLUSTERS.AVENTINE,
    geo: geo(41.88445, 12.47975, 'Basilica di Santa Sabina'),
    interestTags: ['art', 'religion-belief', 'history'],
    timeCostMin: 6,
    whyWorthIt: 'Fifth-century wooden doors still carry one of the earliest Crucifixion scenes in art.',
    archetype: ARCHETYPES.CHURCH_DETAIL,
    lookHere: 'The cypress doors are in the porch. Find the panel where three figures stand against a wall-like cross.',
    body: 'Santa Sabina keeps rare early-Christian wood carving. The Crucifixion panel is debated in details; the doors themselves are the surviving object.',
    accessNotes: 'Church opening hours. Quiet interior. No ticket for the porch doors.',
    audio: MEDIA_STATUS.PLANNED,
    indoorOutdoor: 'indoor',
    weatherFit: 'rain-ok',
    urbanComfort: 'off-trail',
    historicalGuardrail: 'Do not date every panel as 432 as if each scene were unsigned fact. Flag the Crucifixion identification as scholarly.',
    intrinsicPriority: 72,
  }),
  d(4, {
    title: 'Bocca della Verità',
    clusterId: ROME_CLUSTERS.FORUM_BOARIUM,
    geo: geo(41.88815, 12.48145, 'Santa Maria in Cosmedin portico'),
    interestTags: ['folklore', 'iconic-sights', 'people-everyday'],
    avoidTags: ['warfare'],
    timeCostMin: 4,
    whyWorthIt: 'A drain-cover face became Rome’s most famous lie detector — folklore, not ancient justice.',
    archetype: ARCHETYPES.FOLKLORE,
    lookHere: 'In the portico of Santa Maria in Cosmedin. The marble disk is on the left wall.',
    body: 'The Mouth of Truth is likely a Roman drain or fountain mask. The biting-hand legend is medieval/modern folklore, later filmed.',
    accessNotes: 'Often a queue. Portico access; church separate. Small offering box sometimes present.',
    audio: MEDIA_STATUS.PLANNED,
    crowdSensitivity: 'high',
    urbanComfort: 'visitor-areas',
    historicalGuardrail: 'Do not present the lie-detector story as ancient Roman law.',
    intrinsicPriority: 64,
  }),
  d(5, {
    title: 'Temple of Hercules Victor',
    shortTitle: 'Hercules Victor',
    clusterId: ROME_CLUSTERS.FORUM_BOARIUM,
    geo: geo(41.88872, 12.48095, 'Piazza della Bocca della Verità'),
    interestTags: ['history', 'architecture-design', 'religion-belief'],
    timeCostMin: 4,
    whyWorthIt: 'A round Greek-style temple still stands in the old cattle market by the Tiber.',
    archetype: ARCHETYPES.ANCIENT_TEMPLE,
    lookHere: 'The round colonnade in the Forum Boarium, beside the rectangular Temple of Portunus.',
    body: 'This is the round temple, often mistaken for Vesta. It is Hercules of the Forum Boarium — Greek marble, Roman market.',
    accessNotes: 'Exterior viewing from the piazza. Interior rarely open.',
    audio: MEDIA_STATUS.NONE,
    historicalGuardrail: 'Do not call it the Temple of Vesta. That is in the Forum.',
    intrinsicPriority: 68,
  }),
  d(6, {
    title: 'Temple of Portunus',
    clusterId: ROME_CLUSTERS.FORUM_BOARIUM,
    geo: geo(41.88915, 12.48105, 'Forum Boarium'),
    interestTags: ['history', 'architecture-design', 'engineering'],
    timeCostMin: 4,
    whyWorthIt: 'A well-preserved river-port temple still reads as a complete Roman porch.',
    archetype: ARCHETYPES.ANCIENT_TEMPLE,
    lookHere: 'The rectangular temple beside Hercules Victor, Ionic columns, high podium.',
    body: 'Portunus watched the river harbour. Survival is partly conversion: it later became a church, which kept the shell standing.',
    accessNotes: 'Usually exterior only.',
    historicalGuardrail: 'Do not collapse Portunus and Hercules into one building.',
    intrinsicPriority: 66,
  }),
  d(7, {
    title: 'Arch of Janus',
    clusterId: ROME_CLUSTERS.VELABRO,
    geo: geo(41.8894, 12.48165, 'Via del Velabro'),
    interestTags: ['history', 'architecture-design', 'hidden-places'],
    timeCostMin: 3,
    whyWorthIt: 'A four-way late-antique arch still marks the old cattle-market crossroads.',
    archetype: ARCHETYPES.MONUMENT,
    lookHere: 'Stand under the quadrifrons if fencing allows; otherwise read all four faces from the street.',
    body: 'The name “Janus” is later. It is a four-fronted arch at the Velabrum crossing, not the shrine of Janus in the Forum.',
    accessNotes: 'Street viewing. Fencing can change after conservation.',
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not equate this with the Janus Geminus of the Forum.',
    intrinsicPriority: 58,
  }),
  d(8, {
    title: 'San Giorgio in Velabro',
    clusterId: ROME_CLUSTERS.VELABRO,
    geo: geo(41.8897, 12.48305, 'Via del Velabro'),
    interestTags: ['religion-belief', 'history', 'architecture-design'],
    timeCostMin: 5,
    whyWorthIt: 'A quiet deaconry church sits on the marsh street that once linked Forum and river.',
    archetype: ARCHETYPES.CHURCH_DETAIL,
    lookHere: 'The porch and campanile on Via del Velabro, a few steps from the Arch of Janus.',
    body: 'Velabrum was the low ground between Palatine and river. The church is early-medieval on older fabric; 1993 bomb damage was later repaired.',
    accessNotes: 'Opening hours vary. Free when open.',
    indoorOutdoor: 'mix',
    urbanComfort: 'off-trail',
    historicalGuardrail: 'Do not invent a Constantine foundation as fact.',
    intrinsicPriority: 55,
  }),
  d(9, {
    title: 'Theatre of Marcellus',
    clusterId: ROME_CLUSTERS.GHETTO,
    geo: geo(41.89194, 12.47978, 'Via del Teatro di Marcello'),
    interestTags: ['history', 'architecture-design', 'iconic-sights'],
    timeCostMin: 6,
    whyWorthIt: 'An Augustan theatre still carries apartments in its upper arches.',
    archetype: ARCHETYPES.MONUMENT,
    lookHere: 'From Via del Teatro di Marcello: travertine arcades below, later palazzo above.',
    body: 'Dedicated to Augustus’s nephew Marcellus. The upper floors became a fortress, then palazzo — the stacking is the story.',
    accessNotes: 'Exterior always. Archaeological area hours vary.',
    audio: MEDIA_STATUS.PLANNED,
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not call it the Colosseum’s twin as if it were the same building type without nuance (theatre vs amphitheatre).',
    intrinsicPriority: 80,
  }),
  d(10, {
    title: "Portico d'Ottavia",
    clusterId: ROME_CLUSTERS.GHETTO,
    geo: geo(41.8924, 12.4785, 'Via del Portico d’Ottavia'),
    interestTags: ['history', 'people-everyday', 'architecture-design'],
    timeCostMin: 4,
    whyWorthIt: 'Augustus’s portico became the fish market propylaeum of the Ghetto.',
    archetype: ARCHETYPES.MONUMENT,
    lookHere: 'The brick-and-marble gateway on Via del Portico d’Ottavia, with the church of Sant’Angelo in Pescheria behind.',
    body: 'Octavia’s portico framed temples and a library. Medieval Rome reused the gate for the fish market; the Latin fish-measure inscription is later civic reuse.',
    accessNotes: 'Street level, free. Ghetto streets immediately west.',
    historicalGuardrail: 'Keep Ghetto history distinct from the Augustan building; both belong here, stacked.',
    intrinsicPriority: 74,
  }),
  d(11, {
    title: "Pietre d'Inciampo",
    shortTitle: 'Stumbling stones',
    clusterId: ROME_CLUSTERS.GHETTO,
    geo: geo(41.89255, 12.47805, 'Representative Ghetto stones — not a single canonical stone'),
    interestTags: ['history', 'people-everyday', 'politics-power'],
    timeCostMin: 3,
    whyWorthIt: 'Small brass names in the pavement mark where deported neighbors once lived.',
    archetype: ARCHETYPES.STREET_FRAGMENT,
    lookHere: 'Look down at doorways on Via del Portico d’Ottavia and nearby streets. Each stone is a person, not a monument.',
    body: 'Stolpersteine in Rome are a distributed memorial. This pin is a representative Ghetto location, not the only stone.',
    accessNotes: 'Always visible underfoot. Do not step on them as a photo prop.',
    crowdSensitivity: 'low',
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not invent a single “the” stone. Do not reduce Shoah memory to a scavenger hunt.',
    intrinsicPriority: 78,
  }),
  d(12, {
    title: 'Fontana delle Tartarughe',
    shortTitle: 'Turtle Fountain',
    clusterId: ROME_CLUSTERS.MATTEI,
    geo: geo(41.89388, 12.47755, 'Piazza Mattei'),
    interestTags: ['art', 'hidden-places', 'architecture-design'],
    timeCostMin: 4,
    whyWorthIt: 'Four youths and four turtles turn a small Ghetto piazza into a late-Renaissance joke.',
    archetype: ARCHETYPES.MONUMENT,
    lookHere: 'Piazza Mattei. The turtles sit on the upper rim — later Bernini-workshop additions.',
    body: 'Della Porta designed the fountain; the turtles are a later touch. The square is the Mattei family’s front yard.',
    accessNotes: 'Open piazza. Free.',
    historicalGuardrail: 'Do not attribute the whole fountain to Bernini.',
    intrinsicPriority: 73,
  }),
  d(13, {
    title: 'Palazzo Mattei courtyard',
    clusterId: ROME_CLUSTERS.MATTEI,
    geo: geo(41.89405, 12.47835, 'Palazzo Mattei di Giove'),
    interestTags: ['art', 'architecture-design', 'hidden-places'],
    timeCostMin: 4,
    whyWorthIt: 'A courtyard packed with ancient sculpture, still a palazzo’s private antiquity collection.',
    archetype: ARCHETYPES.COURTYARD,
    lookHere: 'Enter the courtyard from Via Michelangelo Caetani if the gate is open. Reliefs climb the walls.',
    body: 'The Mattei showed Rome they owned antiquity by building it into the stairs. Access is a courtyard glance, not a museum ticket.',
    accessNotes: 'Courtyard sometimes open during office hours. Do not enter apartments.',
    indoorOutdoor: 'mix',
    urbanComfort: 'off-trail',
    historicalGuardrail: 'Do not promise a public museum circuit.',
    intrinsicPriority: 62,
  }),
  d(14, {
    title: 'Borromini Perspective, Palazzo Spada',
    shortTitle: 'Borromini perspective',
    clusterId: ROME_CLUSTERS.CAMPO,
    geo: geo(41.89415, 12.47185, 'Palazzo Spada'),
    interestTags: ['architecture-design', 'art', 'hidden-places', 'engineering'],
    timeCostMin: 5,
    whyWorthIt: 'A corridor that looks 30 metres long is about eight — forced perspective in a palazzo garden.',
    archetype: ARCHETYPES.PERSPECTIVE,
    lookHere: 'Palazzo Spada courtyard. View the gallery from the marked viewpoint; do not walk it as if it were a real colonnade.',
    body: 'Borromini and the mathematician Bitonti shrank columns and raised the floor. The statue at the end is small. This is optics, not a lost wing.',
    accessNotes: 'Galleria Spada ticket for reliable access. Courtyard glimpse is not always enough.',
    audio: MEDIA_STATUS.PLANNED,
    visual: MEDIA_STATUS.PLANNED,
    indoorOutdoor: 'mix',
    weatherFit: 'rain-ok',
    historicalGuardrail: 'Do not call it a magic trick without naming forced perspective. Length numbers vary slightly by source; keep them approximate.',
    intrinsicPriority: 84,
  }),
  d(15, {
    title: 'Palazzo Farnese',
    clusterId: ROME_CLUSTERS.CAMPO,
    geo: geo(41.8947, 12.47065, 'Piazza Farnese'),
    interestTags: ['architecture-design', 'art', 'politics-power'],
    timeCostMin: 4,
    whyWorthIt: 'Rome’s great High Renaissance palazzo is now the French Embassy — still a power façade.',
    archetype: ARCHETYPES.PALAZZO,
    lookHere: 'Piazza Farnese. Michelangelo’s cornice and the two granite tubs from the Baths of Caracalla.',
    body: 'Sangallo, Michelangelo, and others built the Farnese palace. Interior frescoes are not a casual walk-in.',
    accessNotes: 'Façade always. Interiors by embassy/French cultural booking only.',
    urbanComfort: 'visitor-areas',
    historicalGuardrail: 'Do not imply tourists can wander the Carracci gallery without a booked visit.',
    intrinsicPriority: 71,
  }),
  d(16, {
    title: 'Passetto del Biscione',
    clusterId: ROME_CLUSTERS.CAMPO,
    geo: geo(41.89545, 12.47305, 'Via del Biscione / Passetto'),
    interestTags: ['hidden-places', 'people-everyday', 'architecture-design'],
    timeCostMin: 3,
    whyWorthIt: 'A painted passage still threads a block of Campo de’ Fiori housing.',
    archetype: ARCHETYPES.STREET_FRAGMENT,
    lookHere: 'The covered alley off Via del Biscione. Look up at the vault fresco, not only the shops.',
    body: 'A passetto is a short covered street. This one keeps a domestic ceiling painting above ordinary foot traffic.',
    accessNotes: 'Public passage. Tight for crowds.',
    urbanComfort: 'off-trail',
    historicalGuardrail: 'Do not invent a papal escape-tunnel claim; that is the Vatican Passetto di Borgo.',
    intrinsicPriority: 60,
  }),
  d(17, {
    title: "Curve of Pompey's Theatre",
    shortTitle: 'Via di Grottapinta',
    clusterId: ROME_CLUSTERS.CAMPO,
    geo: geo(41.89528, 12.47355, 'Via di Grottapinta'),
    interestTags: ['history', 'hidden-places', 'architecture-design'],
    timeCostMin: 4,
    whyWorthIt: 'The street still bends with Pompey’s cavea — the theatre is in the plan of the block.',
    archetype: ARCHETYPES.STREET_FRAGMENT,
    lookHere: 'Walk Via di Grottapinta and feel the curve. Houses sit on the seating of Pompey’s theatre.',
    body: 'Pompey’s theatre was concrete and marble. The cavea survives as a street arc. Caesar died in the porticus, not on this exact cobble — nearby Largo Argentina is the better assassination pin.',
    accessNotes: 'Public street. Free.',
    relatedContentIds: ['w20'],
    urbanComfort: 'off-trail',
    historicalGuardrail: 'Do not place Caesar’s murder on Grottapinta itself.',
    intrinsicPriority: 69,
  }),
  d(18, {
    title: 'Pasquino',
    clusterId: ROME_CLUSTERS.CAMPO,
    geo: geo(41.89748, 12.47235, 'Piazza di Pasquino'),
    interestTags: ['people-everyday', 'politics-power', 'art', 'hidden-places'],
    timeCostMin: 3,
    whyWorthIt: 'A battered Hellenistic statue became Rome’s noticeboard for anonymous satire.',
    archetype: ARCHETYPES.TALKING_STATUE,
    lookHere: 'The corner torso on Piazza di Pasquino, behind Piazza Navona. Read whatever paper is taped today.',
    body: 'Talking statues received pasquinades. The sculpture is a fragment; the voice is the city’s.',
    accessNotes: 'Always visible. Notes come and go.',
    audio: MEDIA_STATUS.PLANNED,
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not invent a specific ancient identity as settled fact; the nickname is early-modern.',
    intrinsicPriority: 76,
  }),
  d(19, {
    title: 'San Luigi dei Francesi — Caravaggios',
    shortTitle: 'San Luigi Caravaggios',
    clusterId: ROME_CLUSTERS.PANTHEON,
    geo: geo(41.89955, 12.47455, 'San Luigi dei Francesi'),
    interestTags: ['art', 'religion-belief', 'iconic-sights'],
    timeCostMin: 8,
    whyWorthIt: 'Three Caravaggio canvases of St Matthew still hang in the chapel they were painted for.',
    archetype: ARCHETYPES.PAINTING,
    lookHere: 'Contarelli Chapel, left aisle. Wait for the lighting box if the paintings are dim.',
    body: 'Calling, Inspiration, and Martyrdom of St Matthew. This is a chapel visit, not a museum queue with audio tour infrastructure.',
    accessNotes: 'Free church. Coin/light box often required. No photos if posted. Closed during Mass.',
    audio: MEDIA_STATUS.PLANNED,
    indoorOutdoor: 'indoor',
    weatherFit: 'rain-ok',
    crowdSensitivity: 'high',
    urbanComfort: 'visitor-areas',
    historicalGuardrail: 'Do not narrate every iconographic dispute. Keep to what is on the wall.',
    intrinsicPriority: 92,
  }),
  d(20, {
    title: "Sant'Agostino — Madonna di Loreto",
    shortTitle: 'Madonna di Loreto',
    clusterId: ROME_CLUSTERS.PANTHEON,
    geo: geo(41.90095, 12.4744, "Sant'Agostino"),
    interestTags: ['art', 'religion-belief', 'people-everyday'],
    timeCostMin: 6,
    whyWorthIt: 'Caravaggio’s pilgrims kneel with dirty feet — devotion painted at street level.',
    archetype: ARCHETYPES.PAINTING,
    lookHere: 'Cavalletti Chapel. The Madonna stands in a doorway; the pilgrims’ feet are the scandal.',
    body: 'Also called Madonna of the Pilgrims. Nearby Raphael’s Isaiah is a different stop in the same church.',
    accessNotes: 'Free church hours. Quiet.',
    audio: MEDIA_STATUS.PLANNED,
    indoorOutdoor: 'indoor',
    weatherFit: 'rain-ok',
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not collapse this canvas with the San Luigi cycle.',
    intrinsicPriority: 81,
  }),
  d(21, {
    title: 'Pie di Marmo',
    clusterId: ROME_CLUSTERS.PANTHEON,
    geo: geo(41.89785, 12.47905, 'Via del Pie di Marmo'),
    interestTags: ['hidden-places', 'history', 'art'],
    timeCostMin: 2,
    whyWorthIt: 'A colossal marble foot still waits on the street that is named after it.',
    archetype: ARCHETYPES.STREET_FRAGMENT,
    lookHere: 'Corner of Via del Pie di Marmo. It is a fragment of a cult statue, not a joke sculpture.',
    body: 'Probably from a temple statue of ancient Iseum/Serapeum fabric. The street kept the nickname.',
    accessNotes: 'Always visible. 30 seconds if you only glance.',
    audio: MEDIA_STATUS.NONE,
    crowdSensitivity: 'low',
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not invent a precise god without a hedge; identification is fragmentary.',
    intrinsicPriority: 63,
  }),
  d(22, {
    title: "Bernini's Elephant",
    shortTitle: 'Minerva elephant',
    clusterId: ROME_CLUSTERS.PANTHEON,
    geo: geo(41.89792, 12.47735, 'Piazza della Minerva'),
    interestTags: ['art', 'iconic-sights', 'hidden-places'],
    timeCostMin: 3,
    whyWorthIt: 'An elephant carries an obelisk behind the Pantheon — Bernini’s smallest Roman joke.',
    archetype: ARCHETYPES.MONUMENT,
    lookHere: 'Piazza della Minerva, east of the Pantheon. Walk around the elephant; the obelisk is Egyptian, the beast is Baroque.',
    body: 'Obelisk from the Iseum. Elephant designed by Bernini, carved by Ercole Ferrata. Nickname Pulcino della Minerva is later affection.',
    accessNotes: 'Open piazza. Free.',
    relatedContentIds: ['w17'],
    crowdSensitivity: 'medium',
    urbanComfort: 'visitor-areas',
    historicalGuardrail: 'Do not credit Bernini with carving the elephant himself.',
    intrinsicPriority: 88,
  }),
  d(23, {
    title: 'Tiber flood markers',
    shortTitle: 'Minerva flood marks',
    clusterId: ROME_CLUSTERS.PANTHEON,
    geo: geo(41.89805, 12.47805, 'Santa Maria sopra Minerva / nearby flood plaques'),
    interestTags: ['history', 'engineering', 'people-everyday'],
    timeCostMin: 4,
    whyWorthIt: 'Marble lines on church walls still record how high the Tiber rose into the centro.',
    archetype: ARCHETYPES.STREET_FRAGMENT,
    lookHere: 'Look for inscribed waterlines on Santa Maria sopra Minerva and nearby church flanks. Heights are labelled by year.',
    body: 'Rome marked floods on sacred walls. The river is walled now; the inscriptions are the memory.',
    accessNotes: 'Street reading. Several related plaques exist; this pin is the Minerva cluster, not a unique stone.',
    historicalGuardrail: 'Do not treat one plaque as the only flood record in Rome.',
    intrinsicPriority: 61,
  }),
  d(24, {
    title: "Sant'Ignazio — the dome that is not there",
    shortTitle: "Sant'Ignazio dome",
    clusterId: ROME_CLUSTERS.PANTHEON,
    geo: geo(41.89898, 12.47985, "Sant'Ignazio di Loyola"),
    interestTags: ['art', 'architecture-design', 'religion-belief', 'hidden-places'],
    timeCostMin: 6,
    whyWorthIt: 'Andrea Pozzo painted a dome on a flat ceiling — stand on the disk and it rounds.',
    archetype: ARCHETYPES.PERSPECTIVE,
    lookHere: 'Stand on the marble disk in the nave marked for the view. Then step off and watch the dome collapse into a saucer.',
    body: 'The order could not raise a real dome. Pozzo’s fresco supplies one from the correct station point. A fake dome is still a painting.',
    accessNotes: 'Free church. Best in daylight. Ceiling is not a Reveal asset in-app yet.',
    audio: MEDIA_STATUS.PLANNED,
    visual: MEDIA_STATUS.PLANNED,
    indoorOutdoor: 'indoor',
    weatherFit: 'rain-ok',
    crowdSensitivity: 'medium',
    urbanComfort: 'visitor-areas',
    historicalGuardrail: 'Do not describe an in-app 3D reconstruction. Visual treatment is planned, not shipping.',
    intrinsicPriority: 90,
  }),
  d(25, {
    title: 'Chiesa del Gesù',
    shortTitle: 'Il Gesù',
    clusterId: ROME_CLUSTERS.VENEZIA,
    geo: geo(41.89592, 12.47975, 'Piazza del Gesù'),
    interestTags: ['religion-belief', 'art', 'architecture-design'],
    timeCostMin: 6,
    whyWorthIt: 'The Jesuit mother church still explodes in Baroque gold after a relatively sober façade.',
    archetype: ARCHETYPES.CHURCH_DETAIL,
    lookHere: 'Enter and look up: Gaulli’s ceiling. Then the chapel of St Ignatius on the left.',
    body: 'Il Gesù set a Counter-Reformation pattern: façade as billboard, interior as theatre. This is a visit, not a full Jesuit history lecture.',
    accessNotes: 'Free church hours. Dress modestly.',
    audio: MEDIA_STATUS.PLANNED,
    indoorOutdoor: 'indoor',
    weatherFit: 'rain-ok',
    urbanComfort: 'visitor-areas',
    historicalGuardrail: 'Do not turn the church into an anti-Jesuit tract or a miracle catalogue.',
    intrinsicPriority: 77,
  }),
  d(26, {
    title: 'Palazzo Grazioli',
    clusterId: ROME_CLUSTERS.VENEZIA,
    geo: geo(41.89645, 12.48165, 'Via del Plebiscito'),
    interestTags: ['politics-power', 'people-everyday', 'architecture-design'],
    timeCostMin: 3,
    whyWorthIt: 'A palazzo on the Venezia axis that later politics kept in the newspapers.',
    archetype: ARCHETYPES.POLITICAL,
    lookHere: 'Via del Plebiscito façade near Piazza Venezia. This is a noticing stop, not a tour inside.',
    body: 'An aristocratic palazzo later associated with contemporary political residence. ChronoWalk does not narrate living private lives.',
    accessNotes: 'Exterior only. Security presence possible. Do not loiter at doors.',
    urbanComfort: 'visitor-areas',
    historicalGuardrail: 'No partisan commentary. No interior claims. Treat as urban power architecture.',
    intrinsicPriority: 40,
  }),
  d(27, {
    title: 'Il Facchino',
    clusterId: ROME_CLUSTERS.CORSO,
    geo: geo(41.89845, 12.48155, 'Via Lata / near Via del Corso'),
    interestTags: ['people-everyday', 'art', 'hidden-places'],
    timeCostMin: 2,
    whyWorthIt: 'A fountain-porter still spills water — another of Rome’s talking statues.',
    archetype: ARCHETYPES.TALKING_STATUE,
    lookHere: 'The wall fountain of a caped porter. The face is the point of the old satire.',
    body: 'Il Facchino is a fountain figure, not a portrait of a famous man despite later jokes. Pair mentally with Pasquino, not with Bernini fountains.',
    accessNotes: 'Street wall. Easy to miss.',
    crowdSensitivity: 'low',
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not identify the face as a specific historical person as fact.',
    intrinsicPriority: 52,
  }),
  d(28, {
    title: 'Madama Lucrezia',
    clusterId: ROME_CLUSTERS.VENEZIA,
    geo: geo(41.89628, 12.48055, 'Piazza San Marco'),
    interestTags: ['art', 'people-everyday', 'hidden-places', 'history'],
    timeCostMin: 3,
    whyWorthIt: 'A colossal female bust sits in a tiny square — the only female talking statue.',
    archetype: ARCHETYPES.TALKING_STATUE,
    lookHere: 'Piazza San Marco, beside Palazzo Venezia. The bust is a reused ancient fragment with an early-modern nickname.',
    body: 'Madama Lucrezia is part of the talking-statue set. Ancient sculpture, later voice.',
    accessNotes: 'Open square. Free.',
    relatedContentIds: ['d_rome_18'],
    urbanComfort: 'lively',
    historicalGuardrail: 'Do not invent a precise ancient sitter.',
    intrinsicPriority: 54,
  }),
  d(29, {
    title: 'Palazzo Venezia balcony',
    clusterId: ROME_CLUSTERS.VENEZIA,
    geo: geo(41.8962, 12.48145, 'Piazza Venezia'),
    interestTags: ['politics-power', 'history', 'architecture-design'],
    timeCostMin: 3,
    whyWorthIt: 'The balcony over Piazza Venezia is where twentieth-century speeches used the square as a theatre.',
    archetype: ARCHETYPES.POLITICAL,
    lookHere: 'From the piazza, the balcony on Palazzo Venezia’s façade toward the Victor Emmanuel monument.',
    body: 'Palazzo Venezia is a papal palace later used as Mussolini’s headquarters. The balcony is historically loaded; this stop is a look, not a rally reconstruction.',
    accessNotes: 'View from the piazza. Museum interior is a separate ticket.',
    urbanComfort: 'visitor-areas',
    crowdSensitivity: 'high',
    historicalGuardrail: 'Do not recreate speech as entertainment. Do not omit that this is Fascist-era reuse of a Renaissance palace.',
    intrinsicPriority: 67,
  }),
  d(30, {
    title: 'Galleria Sciarra',
    clusterId: ROME_CLUSTERS.CORSO,
    geo: geo(41.89955, 12.48185, 'Via Marco Minghetti'),
    interestTags: ['art', 'architecture-design', 'hidden-places', 'contemporary-culture'],
    timeCostMin: 4,
    whyWorthIt: 'A Liberty-era courtyard of painted women still hides a block off the Corso.',
    archetype: ARCHETYPES.ARCADE,
    lookHere: 'Enter the galleria from Via Marco Minghetti. Look up: Mazzucchelli’s cycle of feminine virtues.',
    body: 'An 1880s covered courtyard, not ancient Rome. It is the centro’s other chronology — modern Rome inside the same walk.',
    accessNotes: 'Often open daytime as a passage. Respect offices.',
    indoorOutdoor: 'mix',
    weatherFit: 'rain-ok',
    urbanComfort: 'off-trail',
    historicalGuardrail: 'Do not market this as Baroque. It is fin-de-siècle.',
    intrinsicPriority: 65,
  }),
])

export const ROME_DISCOVERY_BY_ID = Object.freeze(
  Object.fromEntries(ROME_DISCOVERIES.map((item) => [item.id, item])),
)
