/**
 * City-specific recommendation metadata for Rome Heroes.
 * Ranker code consumes this shape; other cities can supply the same fields.
 *
 * Interest tags use the city-agnostic taxonomy (history, architecture-design, …).
 * Rome-specific flavor stays in titles and whyWorthIt copy.
 */

export { CONTEXT_INTERESTS, INTEREST_IDS, TIME_BUDGETS } from '../../lib/travelContext/taxonomy.js'

export const CITY_ID = 'rome'

export const COVERAGE_LABELS = Object.freeze({
  'rome-free': 'Free',
  'rome-ancient': 'Ancient Rome',
  'rome-historic-center': 'Historic Center',
  'rome-complete': 'All Central Rome',
})

/**
 * @typedef {{
 *   experienceId: string,
 *   placeId: string,
 *   title: string,
 *   interestTags: string[],
 *   timeCostMin: number,
 *   whyWorthIt: string,
 *   unlockScopes: string[],
 *   intrinsicPriority: number,
 * }} RomeHeroMeta
 */

/** @type {Record<string, RomeHeroMeta>} */
export const ROME_HERO_META = Object.freeze({
  w01: {
    experienceId: 'rome:w01',
    placeId: 'colosseum',
    title: 'The Colosseum',
    interestTags: ['history', 'politics-power', 'architecture-design', 'iconic-sights'],
    timeCostMin: 12,
    whyWorthIt: 'The arena that turned a usurper’s gift into Rome’s most public stage.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 88,
  },
  w02: {
    experienceId: 'rome:w02',
    placeId: 'colosseum-interior',
    title: 'Colosseum interior',
    interestTags: ['history', 'architecture-design', 'engineering', 'hidden-places'],
    timeCostMin: 14,
    whyWorthIt: 'Stand over the missing floor and read the machinery of the games.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 78,
  },
  w03: {
    experienceId: 'rome:w03',
    placeId: 'forum-arch-titus',
    title: 'Arch of Titus',
    interestTags: ['history', 'politics-power', 'art'],
    timeCostMin: 8,
    whyWorthIt: 'Victory carved in stone — the same war that paid for the Colosseum.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 62,
  },
  w04: {
    experienceId: 'rome:w04',
    placeId: 'palatine-hill-cluster',
    title: 'The Palatine',
    interestTags: ['history', 'architecture-design', 'politics-power'],
    timeCostMin: 16,
    whyWorthIt: 'The hill of emperors, where palace and myth share the same terrace.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 70,
  },
  enc_circus: {
    experienceId: 'rome:enc_circus',
    placeId: 'circus-maximus',
    title: 'Circus Maximus View',
    interestTags: ['history', 'architecture-design', 'people-everyday'],
    timeCostMin: 8,
    whyWorthIt: 'Look down on the racetrack that held a city’s entire afternoon.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 55,
  },
  w06: {
    experienceId: 'rome:w06',
    placeId: 'forum-basilica-maxentius',
    title: 'Basilica of Maxentius',
    interestTags: ['architecture-design', 'engineering', 'history'],
    timeCostMin: 8,
    whyWorthIt: 'Concrete vaults that taught Europe how to roof a hall.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 58,
  },
  w07: {
    experienceId: 'rome:w07',
    placeId: 'forum-via-sacra',
    title: 'Via Sacra',
    interestTags: ['people-everyday', 'history', 'politics-power'],
    timeCostMin: 7,
    whyWorthIt: 'The processional street where triumphs, markets, and gossip mixed.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 52,
  },
  w08: {
    experienceId: 'rome:w08',
    placeId: 'forum-temple-vesta',
    title: 'Temple of Vesta',
    interestTags: ['religion-belief', 'history'],
    timeCostMin: 7,
    whyWorthIt: 'The city’s hearth — Rome kept this fire as if the state itself could go out.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 54,
  },
  w10: {
    experienceId: 'rome:w10',
    placeId: 'forum-rostra',
    title: 'The Rostra',
    interestTags: ['politics-power', 'history'],
    timeCostMin: 7,
    whyWorthIt: 'The speaker’s platform where the Republic argued itself into empire.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 50,
  },
  w11_12: {
    experienceId: 'rome:w11_12',
    placeId: 'forum-arch-severus',
    title: 'Arch of Septimius Severus',
    interestTags: ['history', 'politics-power', 'art'],
    timeCostMin: 10,
    whyWorthIt: 'A family carved its claim on the Forum — including the Curia next door.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 60,
  },
  w13: {
    experienceId: 'rome:w13',
    placeId: 'capitoline-hill',
    title: 'Capitoline Hill',
    interestTags: ['history', 'politics-power', 'art', 'iconic-sights'],
    timeCostMin: 10,
    whyWorthIt: 'The sacred summit of the city, now Michelangelo’s civic stage.',
    unlockScopes: ['rome-ancient', 'rome-complete'],
    intrinsicPriority: 64,
  },
  w14: {
    experienceId: 'rome:w14',
    placeId: 'trajan-market',
    title: "Trajan's Market",
    interestTags: ['architecture-design', 'people-everyday', 'engineering'],
    timeCostMin: 12,
    whyWorthIt: 'Rome’s stacked shopping street — empire as a working neighborhood.',
    unlockScopes: ['rome-historic-center', 'rome-complete'],
    intrinsicPriority: 66,
  },
  w15: {
    experienceId: 'rome:w15',
    placeId: 'spanish-steps',
    title: 'Spanish Steps',
    interestTags: ['art', 'people-everyday', 'iconic-sights'],
    timeCostMin: 8,
    whyWorthIt: 'A staircase built to connect a church, a piazza, and a whole social season.',
    unlockScopes: ['rome-historic-center', 'rome-complete'],
    intrinsicPriority: 57,
  },
  w16: {
    experienceId: 'rome:w16',
    placeId: 'fontana-di-trevi',
    title: 'Fontana di Trevi',
    interestTags: ['art', 'architecture-design', 'people-everyday', 'iconic-sights'],
    timeCostMin: 10,
    whyWorthIt: 'Two thousand years of water arriving in a Baroque theatre.',
    unlockScopes: ['rome-historic-center', 'rome-complete'],
    intrinsicPriority: 80,
  },
  w17: {
    experienceId: 'rome:w17',
    placeId: 'pantheon',
    title: 'The Pantheon',
    interestTags: ['architecture-design', 'engineering', 'religion-belief', 'iconic-sights'],
    timeCostMin: 10,
    whyWorthIt: 'The porch of the best-preserved interior in the ancient world — and it is free.',
    unlockScopes: ['rome-free', 'rome-historic-center', 'rome-complete'],
    intrinsicPriority: 100,
  },
  w23: {
    experienceId: 'rome:w23',
    placeId: 'pantheon-interior',
    title: 'Pantheon interior',
    interestTags: ['architecture-design', 'engineering', 'religion-belief', 'hidden-places'],
    timeCostMin: 18,
    whyWorthIt: 'Stand under the oculus. The dome is still the largest unreinforced concrete vault on earth.',
    unlockScopes: ['rome-free', 'rome-historic-center', 'rome-complete'],
    intrinsicPriority: 96,
  },
  w18: {
    experienceId: 'rome:w18',
    placeId: 'piazza-navona',
    title: 'Piazza Navona',
    interestTags: ['art', 'people-everyday', 'iconic-sights'],
    timeCostMin: 10,
    whyWorthIt: 'A stadium became a piazza — Bernini’s fountain still argues in the middle.',
    unlockScopes: ['rome-historic-center', 'rome-complete'],
    intrinsicPriority: 72,
  },
  w19: {
    experienceId: 'rome:w19',
    placeId: 'campo-de-fiori',
    title: "Campo de' Fiori",
    interestTags: ['people-everyday', 'hidden-places', 'history'],
    timeCostMin: 8,
    whyWorthIt: 'A market square that still remembers an execution.',
    unlockScopes: ['rome-historic-center', 'rome-complete'],
    intrinsicPriority: 56,
  },
  w20: {
    experienceId: 'rome:w20',
    placeId: 'largo-argentina',
    title: 'Largo di Torre Argentina',
    interestTags: ['history', 'politics-power', 'hidden-places'],
    timeCostMin: 9,
    whyWorthIt: 'Four Republican temples — and the plot that ended Caesar.',
    unlockScopes: ['rome-historic-center', 'rome-complete'],
    intrinsicPriority: 68,
  },
  w21: {
    experienceId: 'rome:w21',
    placeId: 'castel-sant-angelo',
    title: "Castel Sant'Angelo",
    interestTags: ['history', 'architecture-design', 'politics-power'],
    timeCostMin: 12,
    whyWorthIt: 'Hadrian’s tomb became a fortress, then a papal escape route.',
    unlockScopes: ['rome-historic-center', 'rome-complete'],
    intrinsicPriority: 61,
  },
  w22: {
    experienceId: 'rome:w22',
    placeId: 'appian-way',
    title: 'Via Appia Antica',
    interestTags: ['history', 'hidden-places', 'nature-landscape'],
    timeCostMin: 20,
    whyWorthIt: 'The queen of roads, still straight, still outside the centro.',
    unlockScopes: ['rome-complete'],
    intrinsicPriority: 48,
  },
})
