export const EMPTY_STATE_PRESETS = {
  noGps: {
    icon: 'location',
    title: 'Location access is off',
    body: 'ChronoWalk uses your location to detect arrivals and guide you between landmarks. Enable location for this site in your browser settings, then try again.',
    actionLabel: 'Try location again',
  },
  gpsWaiting: {
    icon: 'location',
    title: 'Finding your location',
    body: 'Hang tight — a GPS fix usually arrives within a few seconds when you are outdoors.',
    actionLabel: null,
  },
  gpsUnavailable: {
    icon: 'location',
    title: 'GPS signal unavailable',
    body: 'We are having trouble reading your position. Try moving to an open area, then give it another go.',
    actionLabel: 'Retry GPS',
  },
  noInternet: {
    icon: 'offline',
    title: 'You appear to be offline',
    body: 'ChronoWalk needs a connection to load maps, directions, and media. Reconnect to continue your tour.',
    actionLabel: 'Try again',
  },
  noAudio: {
    icon: 'audio',
    title: 'Audio story not available',
    body: 'This landmark story has not been published yet. You can still explore the map and visual reveals.',
    actionLabel: 'Got it',
  },
  mediaUnavailable: {
    icon: 'media',
    title: 'This view is not available',
    body: 'The image or comparison could not load right now. Your audio story and map guidance are still here for you.',
    actionLabel: 'Try again',
  },
  mediaComingSoon: {
    icon: 'media',
    title: 'Visual reveal coming soon',
    body: 'The reconstruction for this landmark is being prepared. The audio story is ready whenever you are.',
    actionLabel: null,
  },
  routeUnavailable: {
    icon: 'route',
    title: 'Walking route unavailable',
    body: 'We could not draw a path on the map right now. You can still follow landmarks manually or open directions in another app.',
    actionLabel: 'Try again',
  },
  mapUnavailable: {
    icon: 'route',
    title: 'Map could not load',
    body: 'Something interrupted the walking map. Check your connection and try again — your tour progress is safe.',
    actionLabel: 'Try again',
  },
  directionsUnavailable: {
    icon: 'route',
    title: 'Walking directions unavailable',
    body: 'Turn-by-turn steps are not available from here right now. Try again, or open Google Maps for guidance.',
    actionLabel: 'Try again',
  },
  directionsNeedLocation: {
    icon: 'location',
    title: 'Turn on location for directions',
    body: 'ChronoWalk needs your position to build walking directions from where you are standing.',
    actionLabel: 'Enable location',
  },
  directionsAtDestination: {
    icon: 'journey',
    title: 'You are already here',
    body: 'Head back to the map to explore this landmark and start the audio story.',
    actionLabel: 'Back to map',
  },
  tourCompleted: {
    icon: 'journey',
    eyebrow: 'Journey complete',
    title: 'Tour complete',
    body: 'You visited every stop on this route through ancient Rome. What a walk through history.',
    actionLabel: 'View summary',
    secondaryActionLabel: 'Return to map',
  },
  landmarkUnavailable: {
    icon: 'journey',
    title: 'This landmark could not open',
    body: 'Something interrupted the arrival card. Reopen the stop from the map to try again.',
    actionLabel: 'Try again',
  },
  studioUnavailable: {
    icon: 'media',
    title: 'Creator studio could not load',
    body: 'The asset studio hit a snag. Reload the page to continue editing waypoint media.',
    actionLabel: 'Reload page',
  },
}
