-- Stuck-purchase recovery is an operational procedure, not a tracked migration.
--
-- Reusable schema lives in scripts/paddle-customers-migration.sql.
-- For a synthetic purchases-only unlock example (never production), see:
--   scripts/recover-stuck-purchases.example.sql
--
-- Put real incident SQL in a gitignored *.local.sql / *.private.sql file.
-- Do not commit customer emails, transaction IDs, access tokens, or unlock links.
