export const en = {
  brand: {
    name: 'ChronoWalk',
    city: 'Rome',
  },
  welcome: {
    kicker: 'Rome',
    title: 'A city, composed for the hours you actually have.',
    body: 'Real places, in sequence. The afternoon bends to the minutes you hold.',
    begin: 'Begin',
  },
  onboarding: {
    step: (n: number, total: number) => `${n} of ${total}`,
    interests: {
      kicker: 'The afternoon',
      title: 'What should the hours lean toward?',
      antiquity: 'Antiquity',
      antiquityHint: 'Stone, sequence, the Forum',
      livingCity: 'Living city',
      livingCityHint: 'Piazzas, water, the present tense',
      river: 'The river',
      riverHint: 'Tiber light and the long bank',
    },
    style: {
      kicker: 'Pace',
      title: 'How do you like to move through a place?',
      linger: 'Linger',
      lingerHint: 'Fewer stops. More time inside each one.',
      cover: 'Cover ground',
      coverHint: 'A longer arc. Keep walking.',
      mixed: 'A mix',
      mixedHint: 'Some lingering, some distance.',
    },
    mobility: {
      kicker: 'Ground',
      title: 'Stairs, or not.',
      body: 'The Capitoline climb is stairs. We will not surprise you with them.',
      walking: 'Walking is fine, including stairs',
      limited: 'Keep stairs limited',
    },
    time: {
      kicker: 'Hours',
      title: 'How many minutes do you actually have?',
      minutes: (n: number) => `${n} minutes`,
      hint60: 'A threshold. One strong opening.',
      hint120: 'The Forum afternoon.',
      hint180: 'Arena to hill. A longer day.',
    },
    location: {
      kicker: 'On the street',
      title: 'Location, only while you walk.',
      body: 'ChronoWalk notices when you have arrived. You can still plan the afternoon without it. Background access is never requested.',
      allow: 'Allow while walking',
      skip: 'Plan without location',
    },
    ready: {
      kicker: 'Ready',
      title: 'We’ll compose an afternoon for those minutes.',
      body: 'Rome, from published places. One walk, not a catalogue.',
      compose: 'Compose the afternoon',
    },
    continue: 'Continue',
  },
  composing: {
    kicker: 'Composing',
    title: 'Fragments of a documented sequence.',
    seeDraft: 'See the afternoon',
    fragments: ['Arena', 'Arch', 'Vault', 'Way'],
  },
  home: {
    kicker: 'Today in Rome',
    start: 'Start this walk',
    openScore: 'See the sequence',
    why: 'Why this route',
    adjust: 'Adjust',
    settings: 'Settings',
    character: 'A Forum afternoon — arena, triumph, and a room held back.',
    walkingApprox: 'Walking times are approximate',
    payoff: 'Ends on a sealed later room.',
    activeKicker: 'In progress',
    activeBody: 'The afternoon is underway. You can pick up exactly where you left it.',
    resume: 'Resume walking',
  },
  score: {
    kicker: 'The sequence',
    walk: 'Walk',
    walkUnpublished: 'A short walk',
    minutes: (n: number) => `${n} min`,
    sealed: 'Sealed until you choose',
    start: 'Walk this afternoon',
    back: 'Back',
    hero: 'Open',
    discovery: 'A closer look',
    reveal: 'Reveal',
    mystery: 'Later',
  },
  why: {
    kicker: 'Why this',
    title: 'Why this afternoon, and not another.',
    antiquity: 'You asked for antiquity. This afternoon stays with stone, sequence, and the Forum.',
    livingCity:
      'You also marked the living city. This draft still opens on the documented Forum sequence.',
    river: 'The river is noted. This afternoon still holds to the published Forum walk.',
    time: (minutes: number) =>
      `Shaped for about ${minutes} minutes, using published visit times and the walks we actually have.`,
    sequence: 'The stops stay in the order Rome already walks — not reshuffled for effect.',
    alternative:
      'Another afternoon — around the Pantheon, squares and water — waits for a different day.',
    back: 'Back',
  },
  adjust: {
    kicker: 'Adjust',
    title: 'Change the hours. The afternoon will be rewritten.',
    body: 'Three published lengths. The walk is replaced as a whole — it is not trimmed by hand.',
    m60: 'About an hour',
    m120: 'Two hours',
    m180: 'Three hours',
  },
  walk: {
    kicker: 'Walking',
    next: 'Next',
    here: 'I’m here',
    arrivedOffer: 'You may have arrived',
    map: 'Map',
    list: 'List',
    control: 'Route',
    planning: 'Following the sequence',
    gpsOk: 'Location on',
    gpsWeak: 'Location is coarse',
    gpsDenied: 'Location off — use the list',
    noDistance: 'Keep to the stones',
  },
  arrival: {
    kicker: 'Arrival',
    titleFallback: 'This place',
    confirm: 'Confirm I’m here',
    confirmed: 'You’re here',
    begin: 'Begin',
    beginHint: 'Confirm first. The story waits.',
    look: 'Look',
  },
  control: {
    kicker: 'Route',
    title: 'The rest of the afternoon.',
    list: 'List',
    map: 'Map',
    skip: 'Skip this stop',
    back: 'Back to walking',
    settings: 'Settings',
  },
  list: {
    kicker: 'Remainder',
    now: 'Now',
  },
  resume: {
    kicker: 'Welcome back',
    body: 'Same place. Same hour. The afternoon does not start over.',
    continue: 'Continue',
    close: 'Close the afternoon',
  },
  hero: {
    kicker: 'Listen',
    enter: 'Enter',
    complete: 'Continue',
    look: 'Look at',
  },
  discovery: {
    kicker: 'A closer look',
    complete: 'Continue',
  },
  mystery: {
    sealedKicker: 'Held back',
    takeMe: 'Take me there',
    reveal: 'Reveal it now',
    keepSealed: 'Keep it sealed',
    detour: (n: number) => `About ${n} minutes aside`,
    detourUnknown: 'A short detour',
    revealedKicker: 'The later room',
    thenNow: 'Then / Now',
  },
  thenNow: {
    kicker: 'Then / Now',
    hold: 'Press and hold to see then',
    now: 'Now',
    then: 'Then',
    complete: 'Continue',
    credit: 'ChronoWalk photography',
  },
  complete: {
    kicker: 'Held',
    body: 'No points. The rest of the afternoon can still change.',
    next: 'What next',
  },
  fork: {
    kicker: 'A turn',
    recommended: 'Recommended',
    stay: 'Stay in the valley',
    stayImpact: 'Keep the remaining Forum stops. The later room stays sealed until you ask for it.',
    later: 'Take the later room now',
    laterImpact: 'Set the Forum remainder aside. The sealed room becomes what you walk toward next.',
    close: 'End after this stop',
    closeImpact: 'Close the afternoon here. Nothing after this place is kept.',
    follow: 'Follow the plan',
  },
  recompose: {
    kicker: 'Rewriting',
    title: 'The remainder, sliding into a new order.',
    reduce: 'The remainder, rewritten.',
    see: 'See what changed',
  },
  recomposed: {
    kicker: 'Changed',
    title: 'What actually moved.',
    continue: 'Continue walking',
    home: 'Home',
    time: (n: number) =>
      n === 0 ? 'The minutes stay about the same.' : n < 0 ? `About ${Math.abs(n)} minutes less.` : `About ${n} minutes more.`,
    timeUnknown: 'Walking minutes for this change are unpublished.',
    laterRoom: 'The later room is next. The remaining Forum stops are set aside.',
    skipped: 'That stop is out. The rest stays in order.',
    closed: 'The afternoon ends after this stop.',
    swapped: 'The afternoon is now the other published length.',
    kept: 'You kept the current afternoon.',
  },
  skip: {
    kicker: 'Skip',
    title: 'Leave this stop. Nothing is lost.',
    remove: 'Remove it',
  },
  map: {
    kicker: 'Rome',
    title: 'The afternoon, as a line.',
    sketch: 'Published places, drawn as a line.',
    noToken: 'Street map is off in this draft. The sequence is still marked.',
    planning: 'You are planning. Distance from you is not shown.',
    empty: 'Not enough published places to draw a line.',
    save: 'Save',
    saved: 'Saved',
    close: 'Close',
    aboutVisit: (n: number) => `About ${n} minutes here`,
    visitUnknown: 'Visit time unpublished',
  },
  saved: {
    kicker: 'Saved',
    title: 'Kept on this device.',
    body: 'No account. These stay with the phone.',
    empty: 'Nothing saved yet.',
    back: 'Back',
  },
  settings: {
    kicker: 'Settings',
    title: 'Traveler',
    motion: 'Reduce motion',
    motionOn: 'On',
    motionOff: 'Off',
    motionHint: 'Softer transitions. The city still leads.',
    developer: 'Developer information',
    developerBody:
      'This build is a visual draft of ChronoWalk Traveler. Routes come from published Rome stops through a replaceable demo service — not a live City Engine.',
    gallery: 'Screen gallery',
    diagnostics: 'Diagnostics',
    simulate: 'Simulate',
  },
  offline: {
    kicker: 'Offline',
    title: 'The afternoon is still here.',
    body: 'No pretend download. What was already on the device is enough to keep walking.',
    continue: 'Continue the route',
  },
  gps: {
    kicker: 'Location',
    weakTitle: 'The fix is too coarse to claim a distance.',
    weakBody: 'Use the list, or wait for a clearer signal.',
    list: 'Use the list',
    wait: 'Keep waiting',
    seeking: 'Seeking a fix',
    back: 'Back',
  },
  hunt: {
    kicker: 'Visual draft',
    title: 'Detail Hunt',
    body: 'A hunt needs a real clue, a target, and a payoff. Those are not in this Rome draft yet.',
    back: 'Back',
  },
  gallery: {
    kicker: 'Developer',
    title: 'Screen gallery',
    body: 'Not the traveler flow. Status is honest.',
    back: 'Back to settings',
  },
  nav: {
    home: 'Home',
    map: 'Map',
    saved: 'Saved',
    settings: 'Settings',
  },
  actions: {
    back: 'Back',
  },
} as const

export type Copy = typeof en
